---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: litmus-demo
  region: eu-west-1
  version: "1.22"
managedNodeGroups:
  - instanceType: t3.medium
    amiFamily: AmazonLinux2
    name: litmus-demo-ng
    desiredCapacity: 4
    minSize: 1
    maxSize: 4
